name: five_place_app
description: A Flutter app for finding nearby places

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/